import type { Playlist } from "./types";

// 큐레이션 샘플 데이터.
// 실제 서비스에서는 CMS / DB 로 대체하면 됩니다.
export const playlists: Playlist[] = [
  {
    id: "rainy-cafe",
    title: "비 오는 날 카페",
    description: "창밖 빗소리랑 같이 듣는 재즈",
    platform: "youtube",
    url: "https://www.youtube.com/watch?v=HbQBbVuceoE&list=RDHbQBbVuceoE&start_radio=1",
    gradient: "from-slate-400/20 via-blue-800/20 to-ink-900",
    moods: ["차분한", "센티멘탈"],
    works: ["글쓰기", "휴식"],
    trackCount: 30,
    duration: "2시간 05분",
  },
  {
    id: "lofi-workroom",
    title: "로파이 작업실",
    description: "새벽 3시 코딩할 때 그 비트",
    platform: "youtube",
    url: "https://www.youtube.com/watch?v=SyqyRv6NS_U&list=RDSyqyRv6NS_U&start_radio=1",
    gradient: "from-indigo-500/30 via-violet-600/20 to-ink-900",
    moods: ["집중", "차분한"],
    works: ["코딩", "공부"],
    trackCount: 50,
    duration: "3시간 30분",
  },
  {
    id: "ghibli-ost",
    title: "지브리 OST 모음",
    description: "토토로가 옆에 있는 것 같은 오후",
    platform: "youtube",
    url: "https://www.youtube.com/watch?v=sJrJO9ymOBw&list=RDsJrJO9ymOBw&start_radio=1",
    gradient: "from-teal-500/25 via-emerald-800/15 to-ink-900",
    moods: ["몽환적", "차분한"],
    works: ["글쓰기", "디자인"],
    trackCount: 26,
    duration: "1시간 45분",
  },
  {
    id: "city-pop",
    title: "시티팝",
    description: "노을 지는 도쿄, 80년대 감성",
    platform: "youtube",
    url: "https://www.youtube.com/watch?v=Brpdd4RwmXc&list=RDBrpdd4RwmXc&start_radio=1",
    gradient: "from-fuchsia-500/30 via-purple-700/20 to-ink-900",
    moods: ["경쾌한", "활기찬"],
    works: ["디자인", "코딩"],
    trackCount: 28,
    duration: "1시간 50분",
  },
  {
    id: "anime-ost",
    title: "애니 OST 모음",
    description: "오프닝 들으면 텐션 올라가는 그 느낌",
    platform: "youtube",
    url: "https://www.youtube.com/watch?v=RcvU47oOaBg&list=RDRcvU47oOaBg&start_radio=1",
    gradient: "from-rose-500/30 via-orange-700/20 to-ink-900",
    moods: ["활기찬", "센티멘탈"],
    works: ["디자인", "휴식"],
    trackCount: 35,
    duration: "2시간 20분",
  },
  {
    id: "hogwarts-arrival",
    title: "호그와트 입학",
    description: "내가 마법사가 된 것 같은 집중력",
    platform: "youtube",
    url: "https://www.youtube.com/watch?v=Crp_OSv8bc0&list=RDCrp_OSv8bc0&start_radio=1",
    gradient: "from-amber-500/25 via-indigo-800/25 to-ink-900",
    moods: ["집중", "몽환적"],
    works: ["공부", "글쓰기"],
    trackCount: 22,
    duration: "1시간 35분",
  },
  {
    id: "dawn-k-indie",
    title: "새벽 K-인디",
    description: "전화 안 받을 새벽 4시",
    platform: "youtube",
    url: "https://www.youtube.com/watch?v=PRfXz1iN3_o&list=RDPRfXz1iN3_o&start_radio=1",
    gradient: "from-pink-400/20 via-purple-800/20 to-ink-900",
    moods: ["센티멘탈", "몽환적"],
    works: ["글쓰기", "휴식"],
    trackCount: 32,
    duration: "2시간 10분",
  },
  {
    id: "deadline-rush",
    title: "마감이 얼마 남지 않았을때",
    description: "4시간 안에 끝내야 할 때 듣는 음악",
    platform: "youtube",
    url: "https://www.youtube.com/watch?v=mrvJt2fZOEw&list=RDmrvJt2fZOEw&start_radio=1",
    gradient: "from-red-500/30 via-orange-700/20 to-ink-900",
    moods: ["집중", "활기찬"],
    works: ["코딩", "공부"],
    trackCount: 40,
    duration: "2시간 40분",
  },
];
